### ISSUE TITLE
Add global.json

### ISSUE THREAD

**Issue by crisberrios** [ajepst/XlsToEf#15]
Installing VS2017 breaks the build as dotnet-cli preview3 breaks compatibility with preview2 projects. Specifying latest preview2 version (3177) in global.json prevents this behavior from happening.

**Comment by ajepst** [comment]
@crisberrios  Is there any way we can be ... slightly less specific while still blocking using the preview? Specifying EXACTLY 3177, I suppose it won't build if somebody's a tiny point-version off unless they change their version of the framework, which seems pretty inconvenient. (esp if they have another project that has a different point version installed)

**Comment by crisberrios** [comment]
For now there isn't. There's an open issue on dotnet repo https://github.com/dotnet/core-setup/issues/679

Specifying 3177-1 should be *safe* as preview2 shouldn't get new versions since the current is preview3

**Comment by ajepst** [comment]
Think I am going to hold off on this as having to rely on a specific might-be-hard-to-obtain version that is a few points away from what someone has  is also pretty troublesome. Instead, once 2017 comes out of beta, which should be very soon (this month?) XlsToEf is getting upgraded all the way up, and then, goodbye to json based project files.

**Comment by ajepst** [comment]
Upgraded to new core csproj fanciness, this should no longer be an issue.
